"""add authentication and challenge management foundation

Revision ID: 005485fe2c1f
Revises: c4f8a19b2d71
Create Date: 2026-09-11 17:25:39.899004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '005485fe2c1f'
down_revision: Union[str, Sequence[str], None] = 'c4f8a19b2d71'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_providers',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('provider_type', sa.Enum('ATS', 'CAREER_SITE', 'JOB_BOARD', 'NETWORKING', 'EMAIL', 'OTHER', name='authprovidertype'), nullable=False),
    sa.Column('base_url', sa.String(length=512), nullable=True),
    sa.Column('authentication_method', sa.Enum('NONE', 'SESSION', 'OAUTH', 'OIDC', 'PASSWORD', 'API_KEY', 'UNKNOWN', name='authenticationmethod'), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id', 'name', name='uq_auth_providers_candidate_name')
    )
    op.create_index(op.f('ix_auth_providers_candidate_id'), 'auth_providers', ['candidate_id'], unique=False)
    op.create_table('auth_provider_states',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('NOT_REQUIRED', 'NOT_CONFIGURED', 'AUTHENTICATED', 'SESSION_EXPIRED', 'AUTHENTICATION_REQUIRED', 'MFA_REQUIRED', 'CAPTCHA_REQUIRED', 'ACCESS_BLOCKED', 'RATE_LIMITED', 'HUMAN_ACTION_REQUIRED', 'ERROR', name='authstate'), nullable=False),
    sa.Column('session_reference', sa.String(length=512), nullable=True),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('authenticated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['provider_id'], ['auth_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_provider_states_provider_id'), 'auth_provider_states', ['provider_id'], unique=True)
    op.create_index(op.f('ix_auth_provider_states_status'), 'auth_provider_states', ['status'], unique=False)
    op.create_table('browser_sessions',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CLOSED', 'SUSPENDED', 'UNKNOWN', name='browsersessionstatus'), nullable=False),
    sa.Column('storage_reference', sa.String(length=512), nullable=True),
    sa.Column('external_session_id', sa.String(length=512), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['auth_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_browser_sessions_candidate_id'), 'browser_sessions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_provider_id'), 'browser_sessions', ['provider_id'], unique=False)
    op.create_index(op.f('ix_browser_sessions_status'), 'browser_sessions', ['status'], unique=False)
    op.create_table('challenges',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_id', sa.String(length=36), nullable=True),
    sa.Column('challenge_type', sa.Enum('CAPTCHA', 'MFA', 'OTP', 'LOGIN_REQUIRED', 'SESSION_EXPIRED', 'BOT_PROTECTION', 'ACCESS_DENIED', 'RATE_LIMIT', 'UNKNOWN_HUMAN_VERIFICATION', name='challengetype'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'HUMAN_ACTION_REQUIRED', 'RESOLVED', 'CANCELLED', 'TIMED_OUT', 'FAILED', name='challengestatus'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='challengeseverity'), nullable=False),
    sa.Column('human_required', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('context_metadata', sa.JSON(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timed_out_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_method', sa.String(length=32), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['auth_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_candidate_id'), 'challenges', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_challenges_provider_id'), 'challenges', ['provider_id'], unique=False)
    op.create_index(op.f('ix_challenges_status'), 'challenges', ['status'], unique=False)
    op.create_index(op.f('ix_challenges_workflow_id'), 'challenges', ['workflow_id'], unique=False)
    op.create_index('uq_challenges_open_provider_type', 'challenges', ['provider_id', 'challenge_type'], unique=True, sqlite_where=sa.text("status IN ('open', 'acknowledged', 'human_action_required')"), postgresql_where=sa.text("status IN ('open', 'acknowledged', 'human_action_required')"))
    op.create_table('secret_references',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('secret_type', sa.Enum('PASSWORD', 'API_KEY', 'OAUTH_TOKEN', 'REFRESH_TOKEN', 'SESSION_COOKIE', 'MFA_SHARED_SECRET', 'UNKNOWN', name='secrettype'), nullable=False),
    sa.Column('external_reference', sa.String(length=512), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'ROTATED', 'REVOKED', 'MISSING', name='secretreferencestatus'), nullable=False),
    sa.Column('rotated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=512), nullable=True),
    sa.Column('is_local_dev_placeholder', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['auth_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_secret_references_candidate_id'), 'secret_references', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_secret_references_provider_id'), 'secret_references', ['provider_id'], unique=False)
    op.create_table('workflow_runs',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('candidate_id', sa.Uuid(), nullable=False),
    sa.Column('provider_id', sa.Uuid(), nullable=False),
    sa.Column('workflow_type', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'PAUSED_HUMAN_ACTION', 'RESUMED', 'COMPLETED', 'CANCELLED', 'TIMED_OUT', 'FAILED', name='workflowstatus'), nullable=False),
    sa.Column('resume_token', sa.Uuid(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('context_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('paused_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['auth_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_runs_candidate_id'), 'workflow_runs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_provider_id'), 'workflow_runs', ['provider_id'], unique=False)
    op.create_index(op.f('ix_workflow_runs_resume_token'), 'workflow_runs', ['resume_token'], unique=True)
    op.create_index(op.f('ix_workflow_runs_status'), 'workflow_runs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_runs_status'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_resume_token'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_provider_id'), table_name='workflow_runs')
    op.drop_index(op.f('ix_workflow_runs_candidate_id'), table_name='workflow_runs')
    op.drop_table('workflow_runs')
    op.drop_index(op.f('ix_secret_references_provider_id'), table_name='secret_references')
    op.drop_index(op.f('ix_secret_references_candidate_id'), table_name='secret_references')
    op.drop_table('secret_references')
    op.drop_index('uq_challenges_open_provider_type', table_name='challenges', sqlite_where=sa.text("status IN ('open', 'acknowledged', 'human_action_required')"), postgresql_where=sa.text("status IN ('open', 'acknowledged', 'human_action_required')"))
    op.drop_index(op.f('ix_challenges_workflow_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_status'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_provider_id'), table_name='challenges')
    op.drop_index(op.f('ix_challenges_candidate_id'), table_name='challenges')
    op.drop_table('challenges')
    op.drop_index(op.f('ix_browser_sessions_status'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_provider_id'), table_name='browser_sessions')
    op.drop_index(op.f('ix_browser_sessions_candidate_id'), table_name='browser_sessions')
    op.drop_table('browser_sessions')
    op.drop_index(op.f('ix_auth_provider_states_status'), table_name='auth_provider_states')
    op.drop_index(op.f('ix_auth_provider_states_provider_id'), table_name='auth_provider_states')
    op.drop_table('auth_provider_states')
    op.drop_index(op.f('ix_auth_providers_candidate_id'), table_name='auth_providers')
    op.drop_table('auth_providers')
    # ### end Alembic commands ###
